export const ADD_MESSAGE = 'ADD_MESSAGE'
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const USER_LIST = 'USER_LIST'
